---
title: 'Distance based predictive techniques'
subtitle: Felipe Lodur
output:
  pdf_document:
    toc: yes
  html_document:
    theme: united
    toc: yes
---


## Euclidean stuff

```{r}
# Distance and similarity measures
library(proxy) # proximity measures

# available measures
summary(pr_DB)

# Taking a sample of iris (for easing distance matrix visualization)
set.seed(1)
iris_sample <- iris[sample(nrow(iris),5),]

# Euclidean distance (equivalents)
dist(as.matrix(iris_sample[,1:4]),method="Minkowski",p=2)
dist(as.matrix(iris_sample[,1:4]),method="Euclidean")

Euclidean <- function(xi,xj){
  sqrt(sum((xi-xj)^2))
}
Euclidean(iris_sample[1,1:4],iris_sample[2,1:4])
```

## Influence of noise

```{r}
noise<-rnorm(5)  
iris_sample[,3] <- iris_sample[,3]+noise
dist(as.matrix(iris_norm[,1:4]),method="Euclidean")
```

```{r}
iris_norm <- as.data.frame(lapply(iris_sample[1:4], normalize))
iris_sample[,3] <- iris_sample[,3]-noise
dist(as.matrix(iris_norm[,1:4]),method="Euclidean")
```

## Some distances

```{r}
dist(as.matrix(iris_norm[,1:4]),method="Manhattan", p=1)
dist(as.matrix(iris_norm[,1:4]),method="supremum")
cor(t(iris_sample[,1:4]))
```


## kNN

```{r}
knn <- function(dataset,query,k=1){
  
  idClass <- ncol(dataset)
  
  Eucl_dist <- apply(dataset,1,function(row){
    sqrt(sum((query-as.numeric(row[1:idClass-1]))^2))
  })
  ids <- sort.list(Eucl_dist,dec=F)[1:k]
  labels <- dataset[ids,idClass]
  
  ret <- list()
  ret$nearest <- ids
  
  if(!is.numeric(dataset[,idClass])){
    # classification problem
    U <- unique(labels)
    R <- rep(0,length(U))
    for (i in 1:length(U)){
       R[i] <- sum(U[i] == labels)
    }
    idx <- which.max(R)
    
    ret$voted <- U
    ret$Nvotes <- R
    ret$pred <- U[idx]
  }
  else{
    ret$pred <- mean(labels)
  }
  
  return(ret)
}

# testing classification
knn(iris_sample,c(5.1,3.4,1.5,0.2),k=1)
```

## DWNN

Distance-Weighted Nearest Neighbors

```{r}
dwnn <- function(dataset, query, sigma=0.5) {
  
  classId = ncol(dataset)
  
  w = apply(dataset,1,function(row){
    eucl <- sqrt(sum((query-row[1:(classId-1)])^2))
    exp(-eucl^2 / (2*sigma^2))
  })
  Y = dataset[,classId]
  pred = sum(w*Y)/ sum(w)
  
  ret <- list()
  ret$weigths <- w
  ret$pred <- pred
  
  return (ret)
}

# testing in modified iris for regression
dwnn(iris_reg,c(5.1,3.4,1.5),sigma = 0.5) # changing sigma val is important

```

## Visualizing it

```{r}
library(caret)


decisionplot <- function(model, data, class = NULL, predict_type = "class",
                         resolution = 100, showgrid = TRUE, ...) {
  
  if(!is.null(class)) cl <- data[,class] else cl <- 1
  data <- data[,1:2]
  k <- length(unique(cl))
  
  plot(data, col = as.integer(cl)+1L, pch = as.integer(cl)+1L, ...)
  
  # make grid
  r <- sapply(data, range, na.rm = TRUE)
  xs <- seq(r[1,1], r[2,1], length.out = resolution)
  ys <- seq(r[1,2], r[2,2], length.out = resolution)
  g <- cbind(rep(xs, each=resolution), rep(ys, time = resolution))
  colnames(g) <- colnames(r)
  g <- as.data.frame(g)
  
  ### guess how to get class labels from predict
  ### (unfortunately not very consistent between models)
  p <- predict(model, g, type = predict_type)
  if(is.list(p)) p <- p$class
  p <- as.factor(p)
  
  if(showgrid) points(g, col = as.integer(p)+1L, pch = ".")
  
  z <- matrix(as.integer(p), nrow = resolution, byrow = TRUE)
  contour(xs, ys, z, add = TRUE, drawlabels = FALSE,
          lwd = 2, levels = (1:(k-1))+.5)
  
  invisible(z)
}

x <- iris[1:150, c("Sepal.Length", "Sepal.Width", "Species")]
model <- knn3(Species ~ ., data=x, k = 1)
decisionplot(model, x, class = "Species", main = "kNN (1)")

model <- knn3(Species ~ ., data=x, k = 10)
decisionplot(model, x, class = "Species", main = "kNN (10)")
```


## Tests

Space for tests with mlbench datasets

```{r}
library(mlbench)

x <- mlbench.circle(100)
x <- cbind(as.data.frame(x$x), factor(x$classes))
colnames(x) <- c("x", "y", "class")

model <- knn3(class ~ ., data=x, k = 1)
decisionplot(model, x, class = "class", main = "kNN (1)")

model <- knn3(class ~ ., data=x, k = 10)
decisionplot(model, x, class = "class", main = "kNN (10)")
```

